development:
  adapter: postgresql
  host: localhost
  database: services_api
  username:
  password:

test:
  adapter: postgresql
  host: localhost
  database: services_api_test
  username:
  password:
